name: publish
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'
      - '.github/workflows/'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish to the Github packages
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN}}